# Generated by Django 5.2.7 on 2025-12-03 16:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('artistid', models.AutoField(db_column='ArtistId', primary_key=True, serialize=False)),
                ('artistname', models.CharField(blank=True, db_column='ArtistName', max_length=255, null=True)),
                ('artist_image', models.ImageField(blank=True, null=True, upload_to='artist_images/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('is_admin', models.BooleanField(default=False)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('profile_image', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eventbookingapp_userprofile',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(blank=True, max_length=100, null=True)),
                ('event_scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('event_description', models.CharField(blank=True, max_length=200, null=True)),
                ('event_available_seats', models.IntegerField(blank=True, null=True)),
                ('event_total_seats', models.IntegerField(blank=True, null=True)),
                ('event_price', models.IntegerField(blank=True, null=True)),
                ('event_location', models.CharField(blank=True, max_length=200, null=True)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('is_sold_out', models.BooleanField(default=False)),
                ('location_name', models.CharField(max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'eventbookingapp_events',
            },
        ),
        migrations.CreateModel(
            name='Bookingdetails',
            fields=[
                ('user_id', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Eventapp.userprofile')),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('seats', models.IntegerField(blank=True, db_column='Seats', null=True)),
                ('event_id', models.IntegerField(blank=True, db_column='Event_id', null=True)),
                ('booking_id', models.CharField(blank=True, db_column='Booking_Id', max_length=100, null=True, unique=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('booking_date', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'eventbookingapp_bookingdetails',
            },
        ),
        migrations.CreateModel(
            name='Eventartist',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('artistid', models.ForeignKey(db_column='ArtistId', on_delete=django.db.models.deletion.DO_NOTHING, to='Eventapp.artists')),
            ],
            options={
                'db_table': 'EventArtist',
            },
        ),
    ]
