# Generated by Django 5.2.5 on 2025-09-11 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(blank=True, max_length=100, null=True)),
                ('event_scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('event_description', models.CharField(blank=True, max_length=200, null=True)),
                ('event_available_seats', models.IntegerField(blank=True, null=True)),
                ('event_total_seats', models.IntegerField(blank=True, null=True)),
                ('event_price', models.IntegerField(blank=True, null=True)),
                ('is_sold_out', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'eventbookingapp_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookingdetails',
            fields=[
                ('user_id', models.AutoField(db_column='User_id', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('seats', models.IntegerField(blank=True, db_column='Seats', null=True)),
                ('event_id', models.IntegerField(blank=True, db_column='Event_id', null=True)),
                ('booking_id', models.CharField(blank=True, db_column='Booking_Id', max_length=100, null=True, unique=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'eventbookingapp_userprofile',
            },
        ),
    ]
