# Generated by Django 5.2.7 on 2026-01-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='events',
            name='event_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userrole',
            field=models.CharField(blank=True, default='Standard User', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='booking_id',
            field=models.CharField(blank=True, db_column='Booking_Id', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
