# Generated by Django 5.2.7 on 2026-09-22 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0002_rename_user_id_bookingdetails_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='booking_id',
            field=models.CharField(blank=True, db_column='Booking_Id', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Eventapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
