# Generated by Django 5.2.5 on 2025-09-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0002_alter_bookingdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookingdetails',
            table='eventbookingapp_bookingdetails',
        ),
    ]
