# Generated by Django 5.2.5 on 2025-09-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0003_alter_bookingdetails_table'),
    ]

    operations = [
    ]
