# Generated by Django 5.2.7 on 2025-12-03 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0005_userprofile_google_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('artistid', models.AutoField(db_column='ArtistId', primary_key=True, serialize=False)),
                ('artistname', models.CharField(blank=True, db_column='ArtistName', max_length=255, null=True)),
                ('artist_image', models.ImageField(blank=True, null=True, upload_to='artist_images/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Artists',
            },
        ),
        migrations.AlterModelOptions(
            name='bookingdetails',
            options={},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Eventartist',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('artistid', models.ForeignKey(db_column='ArtistId', on_delete=django.db.models.deletion.DO_NOTHING, to='Eventapp.artists')),
            ],
            options={
                'db_table': 'EventArtist',
            },
        ),
    ]
