# Generated by Django 5.2.7 on 2025-12-03 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0006_artists_alter_bookingdetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='booking_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='events',
            name='event_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='location_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='user_id',
            field=models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Eventapp.userprofile'),
        ),
    ]
